# ebtree_add_test_suite(NAME <name> SOURCES <files...> [CATEGORIES cat1 cat2 ...])
function(ebtree_add_test_suite)
  cmake_parse_arguments(EBTREE_SUITE "" "NAME" "SOURCES;CATEGORIES" ${ARGN})
  if(NOT EBTREE_SUITE_NAME)
    message(FATAL_ERROR "ebtree_add_test_suite requires NAME")
  endif()
  if(NOT EBTREE_SUITE_SOURCES)
    message(FATAL_ERROR "ebtree_add_test_suite(${EBTREE_SUITE_NAME}) requires SOURCES")
  endif()

  set(_target "ebtree_tests_${EBTREE_SUITE_NAME}")
  set(_dll "${_target}")

  add_library(${_target} SHARED
    ${EBTREE_SUITE_SOURCES}
    "${GTEST_CAPI_DIR}/src/gtest_capi.cpp"
  )

target_include_directories(${_target} PRIVATE
    "${CMAKE_SOURCE_DIR}/cpp/include"
    "${CMAKE_SOURCE_DIR}/test/helpers"
    "${CMAKE_SOURCE_DIR}/test/matrix"
    "${GTEST_CAPI_DIR}/include"
  )
  if(DEFINED EBTEST_GENERATED_INC_DIR)
    target_include_directories(${_target} PRIVATE "${EBTEST_GENERATED_INC_DIR}")
  endif()

  target_link_libraries(${_target} PRIVATE ebtree_core GTest::gtest)

  target_compile_definitions(${_target} PRIVATE
    GTEST_C_API_SHARED_BUILD
    GTEST_LINKED_AS_SHARED_LIBRARY=1
    EBTEST_SUITE_NAME="${EBTREE_SUITE_NAME}"
  )
  if(DEFINED ENV{GITHUB_ACTIONS})
    target_compile_definitions(${_target} PRIVATE EBTEST_CI=1)
  endif()

  if(EBTREE_SUITE_CATEGORIES)
    string(JOIN "," _cats "${EBTREE_SUITE_CATEGORIES}")
    target_compile_definitions(${_target} PRIVATE "EBTEST_CATEGORIES=\"${_cats}\"")
  endif()

  set_target_properties(${_target} PROPERTIES
    OUTPUT_NAME "${_dll}"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/tests"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/tests"
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIG>/tests"
  )

  set_property(GLOBAL APPEND PROPERTY EBTREE_TEST_SUITE_TARGETS "${_target}")
  set_property(GLOBAL APPEND PROPERTY EBTREE_TEST_SUITE_NAMES "${EBTREE_SUITE_NAME}")

  if(EBTREE_SUITE_CATEGORIES)
    foreach(_cat IN LISTS EBTREE_SUITE_CATEGORIES)
      set_property(GLOBAL APPEND PROPERTY "EBTREE_SUITE_${EBTREE_SUITE_NAME}_CATEGORIES" "${_cat}")
    endforeach()
  endif()
endfunction()

function(ebtree_generate_test_suites_inc OUT_FILE)
  get_property(_targets GLOBAL PROPERTY EBTREE_TEST_SUITE_TARGETS)
  get_property(_names GLOBAL PROPERTY EBTREE_TEST_SUITE_NAMES)

  set(_lines "// Auto-generated by CMake - do not edit.\n#pragma once\n\n")
  string(APPEND _lines "struct EbTestSuiteEntry {\n")
  string(APPEND _lines "  const char* name;\n")
  string(APPEND _lines "  const char* dll_basename;\n")
  string(APPEND _lines "  const char* categories;\n")
  string(APPEND _lines "};\n\n")
  string(APPEND _lines "inline constexpr EbTestSuiteEntry kEbTestSuites[] = {\n")

  list(LENGTH _names _count)
  if(_count EQUAL 0)
    string(APPEND _lines "};\n\ninline constexpr int kEbTestSuiteCount = 0;\n")
    file(WRITE "${OUT_FILE}" "${_lines}")
    return()
  endif()

  math(EXPR _last "${_count} - 1")
  foreach(_idx RANGE ${_last})
    list(GET _names ${_idx} _name)
    list(GET _targets ${_idx} _target)
    get_property(_cats GLOBAL PROPERTY "EBTREE_SUITE_${_name}_CATEGORIES")
    if(_cats)
      string(JOIN "," _cat_str "${_cats}")
    else()
      set(_cat_str "")
    endif()
    string(APPEND _lines "  {\"${_name}\", \"ebtree_tests_${_name}\", \"${_cat_str}\"},\n")
  endforeach()

  string(APPEND _lines "};\n\ninline constexpr int kEbTestSuiteCount = ${_count};\n")
  file(WRITE "${OUT_FILE}" "${_lines}")
endfunction()
