param(
    [string]$DataDir,
    [string]$Out
)

function Parse-Case($chunk) {
    $case = @{
        id = ""
        parse = ""
        exec = ""
        follow = ""
        expect_kind = ""
        expect_joins = ""
        expect_subquery = ""
        expect = "ok"
        expect_rows = ""
        expect_value = ""
        setups = @()
    }
    foreach ($line in $chunk -split "`n") {
        $stripped = $line.Trim()
        if (-not $stripped -or $stripped.StartsWith("#")) { continue }
        if ($stripped.StartsWith("case:")) {
            $case.id = $stripped.Substring(5).Trim()
        } elseif ($stripped.StartsWith("parse:")) {
            $case.parse = $stripped.Substring(6).Trim().Trim('"')
        } elseif ($stripped.StartsWith("exec:")) {
            $case.exec = $stripped.Substring(5).Trim().Trim('"')
        } elseif ($stripped.StartsWith("follow:")) {
            $case.follow = $stripped.Substring(7).Trim().Trim('"')
        } elseif ($stripped.StartsWith("setup:")) {
            $case.setups += $stripped.Substring(6).Trim().Trim('"')
        } elseif ($stripped.StartsWith("expect_kind:")) {
            $case.expect_kind = $stripped.Substring(12).Trim()
        } elseif ($stripped.StartsWith("expect_joins:")) {
            $case.expect_joins = $stripped.Substring(13).Trim()
        } elseif ($stripped.StartsWith("expect_subquery:")) {
            $case.expect_subquery = $stripped.Substring(16).Trim()
        } elseif ($stripped.StartsWith("expect:")) {
            $case.expect = $stripped.Substring(7).Trim()
        } elseif ($stripped.StartsWith("expect_rows:")) {
            $case.expect_rows = $stripped.Substring(12).Trim()
        } elseif ($stripped.StartsWith("expect_value:")) {
            $case.expect_value = $stripped.Substring(13).Trim()
        }
    }
    return $case
}

function Load-Matrix($path) {
    $text = (Get-Content -Raw -Encoding UTF8 $path) -replace "`r`n", "`n"
    $chunks = $text -split "`n---`n"
    $out = @()
    foreach ($chunk in $chunks) {
        if ($chunk.Trim()) { $out += Parse-Case $chunk }
    }
    return $out
}

function Escape-C($s) {
    return $s.Replace('\', '\\').Replace('"', '\"')
}

$parseCases = Load-Matrix (Join-Path $DataDir "parse.matrix")
$execCases = @()
foreach ($file in Get-ChildItem (Join-Path $DataDir "*.matrix") | Sort-Object Name) {
    if ($file.Name -eq "parse.matrix" -or $file.Name -eq "perf.matrix") { continue }
    $execCases += Load-Matrix $file.FullName
}
$perfCases = Load-Matrix (Join-Path $DataDir "perf.matrix")

$lines = @(
    "// Auto-generated by gen_sql_matrix_inc.ps1 - do not edit.",
    "#pragma once",
    "",
    "struct SqlParseMatrixCase {",
    "  const char* id;",
    "  const char* sql;",
    "  const char* expect_kind;",
    "  int expect_joins;",
    "  int expect_subquery;",
    "};",
    "",
    "struct SqlExecMatrixCase {",
    "  const char* id;",
    "  const char* setups;",
    "  const char* exec_sql;",
    "  const char* follow_sql;",
    "  const char* expect;",
    "  int expect_rows;",
    "  const char* expect_value;",
    "};",
    "",
    "struct SqlPerfMatrixCase {",
    "  const char* id;",
    "  const char* setups;",
    "  const char* exec_sql;",
    "  const char* expect;",
    "  int expect_rows;",
    "};",
    "",
    "inline const SqlParseMatrixCase kSqlParseMatrixCases[] = {"
)
$parseCount = 0
foreach ($c in $parseCases) {
    if (-not $c.parse) { continue }
    $parseCount++
    $ej = if ($c.expect_joins) { $c.expect_joins } else { "-1" }
    $es = if ($c.expect_subquery) { $c.expect_subquery } else { "-1" }
    $lines += "  {`"$($c.id)`", `"$(Escape-C $c.parse)`", `"$($c.expect_kind)`", $ej, $es},"
}
$lines += "};"
$lines += "inline constexpr int kSqlParseMatrixCaseCount = $parseCount;"
$lines += ""
$lines += "inline const SqlExecMatrixCase kSqlExecMatrixCases[] = {"
$execCount = 0
foreach ($c in $execCases) {
    if (-not $c.exec) { continue }
    $execCount++
    $setups = Escape-C ($c.setups -join ";")
    $er = if ($c.expect_rows) { $c.expect_rows } else { "-1" }
    $lines += "  {`"$($c.id)`", `"$setups`", `"$(Escape-C $c.exec)`", `"$(Escape-C $c.follow)`", `"$($c.expect)`", $er, `"$(Escape-C $c.expect_value)`"},"
}
$lines += "};"
$lines += "inline constexpr int kSqlExecMatrixCaseCount = $execCount;"
$lines += ""
$lines += "inline const SqlPerfMatrixCase kSqlPerfMatrixCases[] = {"
$perfCount = 0
foreach ($c in $perfCases) {
    if (-not $c.exec) { continue }
    $perfCount++
    $setups = Escape-C ($c.setups -join ";")
    $er = if ($c.expect_rows) { $c.expect_rows } else { "-1" }
    $lines += "  {`"$($c.id)`", `"$setups`", `"$(Escape-C $c.exec)`", `"$($c.expect)`", $er},"
}
$lines += "};"
$lines += "inline constexpr int kSqlPerfMatrixCaseCount = $perfCount;"
$lines += ""

$outDir = Split-Path $Out -Parent
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }
[System.IO.File]::WriteAllText($Out, ($lines -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
