#!/usr/bin/env python3
"""Generate sql_matrix_inc.h from test/data/sql/*.matrix"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def parse_case(chunk: str) -> dict:
    case: dict = {
        "id": "",
        "parse": "",
        "exec": "",
        "follow": "",
        "expect_kind": "",
        "expect_joins": "",
        "expect_subquery": "",
        "expect": "ok",
        "expect_rows": "",
        "expect_value": "",
        "setups": [],
    }
    for line in chunk.strip().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("case:"):
            case["id"] = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("parse:"):
            case["parse"] = stripped.split(":", 1)[1].strip().strip('"')
        elif stripped.startswith("exec:"):
            case["exec"] = stripped.split(":", 1)[1].strip().strip('"')
        elif stripped.startswith("follow:"):
            case["follow"] = stripped.split(":", 1)[1].strip().strip('"')
        elif stripped.startswith("setup:"):
            case["setups"].append(stripped.split(":", 1)[1].strip().strip('"'))
        elif stripped.startswith("expect_kind:"):
            case["expect_kind"] = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("expect_joins:"):
            case["expect_joins"] = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("expect_subquery:"):
            case["expect_subquery"] = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("expect:"):
            case["expect"] = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("expect_rows:"):
            case["expect_rows"] = stripped.split(":", 1)[1].strip()
        elif stripped.startswith("expect_value:"):
            case["expect_value"] = stripped.split(":", 1)[1].strip()
    return case


def load_matrix(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    chunks = [c for c in re.split(r"\n---\n", text) if c.strip()]
    return [parse_case(c) for c in chunks]


def escape_c(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_parse_cases(cases: list[dict]) -> str:
    lines = ["inline const SqlParseMatrixCase kSqlParseMatrixCases[] = {"]
    count = 0
    for c in cases:
        if not c["parse"]:
            continue
        count += 1
        lines.append(
            f'  {{"{c["id"]}", "{escape_c(c["parse"])}", "{c["expect_kind"]}", '
            f'{c["expect_joins"] or "-1"}, {c["expect_subquery"] or "-1"}}},'
        )
    lines.append("};")
    lines.append(f"inline constexpr int kSqlParseMatrixCaseCount = {count};")
    return "\n".join(lines)


def emit_exec_cases(cases: list[dict]) -> str:
    lines = ["inline const SqlExecMatrixCase kSqlExecMatrixCases[] = {"]
    count = 0
    for c in cases:
        if not c["exec"]:
            continue
        count += 1
        setups = escape_c(";".join(c["setups"]))
        lines.append(
            f'  {{"{c["id"]}", "{setups}", "{escape_c(c["exec"])}", '
            f'"{escape_c(c["follow"])}", "{c["expect"]}", '
            f'{c["expect_rows"] or "-1"}, "{escape_c(c["expect_value"])}"}},'
        )
    lines.append("};")
    lines.append(f"inline constexpr int kSqlExecMatrixCaseCount = {count};")
    return "\n".join(lines)


def emit_perf_cases(cases: list[dict]) -> str:
    lines = ["inline const SqlPerfMatrixCase kSqlPerfMatrixCases[] = {"]
    count = 0
    for c in cases:
        if not c["exec"]:
            continue
        count += 1
        setups = escape_c(";".join(c["setups"]))
        lines.append(
            f'  {{"{c["id"]}", "{setups}", "{escape_c(c["exec"])}", '
            f'"{c["expect"]}", {c["expect_rows"] or "-1"}}},'
        )
    lines.append("};")
    lines.append(f"inline constexpr int kSqlPerfMatrixCaseCount = {count};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    data_dir = args.data_dir
    parse_cases: list[dict] = []
    exec_cases: list[dict] = []
    for path in sorted(data_dir.glob("*.matrix")):
        cases = load_matrix(path)
        if path.name == "perf.matrix":
            continue
        for c in cases:
            if c["parse"]:
                parse_cases.append(c)
            if c["exec"]:
                exec_cases.append(c)

    perf_cases = load_matrix(data_dir / "perf.matrix")

    out = [
        "// Auto-generated by gen_sql_matrix_inc.py - do not edit.",
        "#pragma once",
        "",
        "struct SqlParseMatrixCase {",
        "  const char* id;",
        "  const char* sql;",
        "  const char* expect_kind;",
        "  int expect_joins;",
        "  int expect_subquery;",
        "};",
        "",
        "struct SqlExecMatrixCase {",
        "  const char* id;",
        "  const char* setups;",
        "  const char* exec_sql;",
        "  const char* follow_sql;",
        "  const char* expect;",
        "  int expect_rows;",
        "  const char* expect_value;",
        "};",
        "",
        "struct SqlPerfMatrixCase {",
        "  const char* id;",
        "  const char* setups;",
        "  const char* exec_sql;",
        "  const char* expect;",
        "  int expect_rows;",
        "};",
        "",
        emit_parse_cases(parse_cases),
        "",
        emit_exec_cases(exec_cases),
        "",
        emit_perf_cases(perf_cases),
        "",
    ]
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
